version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./nginx.proxy.conf:/etc/nginx/conf.d/default.conf:z
    depends_on:
      - app-gin
      - app-nest
    networks:
      - app-common-network

  app-gin:
    build:
      dockerfile: Dockerfile.gin
    container_name: app-gin
    expose:
      - "8080"
    restart: unless-stopped
    volumes:
      - ./.gin.env:/app/.env
    depends_on:
      - db-postgres
      - db-redis
      - app-nest
    networks:
      - app-gin-network
      - app-common-network

  app-nest:
    build:
      dockerfile: Dockerfile.nest
    container_name: app-nest
    expose:
      - "3000"
    env_file: .postgres.env
    restart: unless-stopped
    depends_on:
      - db-postgres
    networks:
      - app-nest-network
      - app-common-network

  db-postgres:
    image: postgres:16-alpine
    container_name: db-postgres
    env_file: .postgres.env
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-gin-network
      - app-nest-network

  db-redis:
    image: redis:alpine
    container_name: db-redis
    env_file: .redis.env
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - app-gin-network

  prisma-studio:
    build:
      dockerfile: Dockerfile.prisma-studio
    container_name: prisma-studio
    ports:
      - "5555:5555"
    env_file: .postgres.env
    restart: unless-stopped
    depends_on:
      - db-postgres
    networks:
      - app-nest-network

networks:
  app-gin-network:
  app-nest-network:
  app-common-network:

volumes:
  pgdata:
  redisdata:
